### ISSUE TITLE
Extracted with 7Zip and the .exe installer and still getting resource errors

### ISSUE THREAD

**Issue by MadWithMusic** [Kuree/Sims4Tools#46]
I've been having this issue since I first downloaded s4pe a few weeks ago, but at the time, all I was doing was retexturing and was able to find a work-around and other softwares that still got the job done. Although now, I'm going back to try again with s4pe because I need to change some flags in the CASP file of a package, but although the CASP file turns out correctly - or at least I think it does - every other file type I've tried gives an error reading resource. I unzipped with 7zip the first time around, but then uninstalled and tried reinstalling with the .exe file. I also tried the tar.gz file and I've tried all the different files of the two most recent versions, and most if not all of the file types give an error reading resource (see pasted error below).

Error reading resource 0x3453CF95-0x80000000-0x9A2209B60CDA4F3B
Front-end Distribution: 
Library Distribution: 

Source: mscorlib
Assembly: mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
Exception has been thrown by the target of an invocation.
----
Stack trace:
   at System.RuntimeMethodHandle._InvokeConstructor(IRuntimeMethodInfo method, Object[] args, SignatureStruct& signature, RuntimeType declaringType)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at S4PIDemoFE.ABuiltInValueControl.<>c__DisplayClassd.<Lookup>b__a(KeyValuePair`2 x)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   at S4PIDemoFE.ABuiltInValueControl.Lookup(UInt32 resourceType, Stream s)
   at S4PIDemoFE.MainForm.getPreviewControl()
----

Source: DDSPanel
Assembly: DDSPanel, Version=1412.28.57.34112, Culture=neutral, PublicKeyToken=null
Unable to load DLL 'squishinterface_x64.dll': The application has failed to start because its side-by-side configuration is incorrect. Please see the application event log for more detail. (Exception from HRESULT: 0x800736B1)
----
Stack trace:
   at System.Drawing.DdsSquish.SquishInterface_64.SquishDecompressImage(Byte* rgba, Int32 width, Int32 height, Byte* blocks, Int32 flags)
   at System.Drawing.DdsSquish.SquishDecompressImage(Byte[] rgba, Int32 width, Int32 height, Byte[] blocks, SquishFlags flags)
   at System.Drawing.DdsSquish.DecompressImage(Byte[] blocks, Int32 width, Int32 height, SquishFlags flags)
   at System.Drawing.Dds..ctor(Stream s)
   at System.Drawing.DdsFile.Load(Stream input, Boolean supportHSV)
   at System.Windows.Forms.DDSPanel.RLELoad(Stream stream, Boolean supportHSV)
   at S4PIDemoFE.RLEControl..ctor(Stream s)
----

 It may or may not be of important, but I'm running Windows Vista.

**Comment by Kuree** [comment]
Hi, it looks like the the dds library cannot display your dds image.
