### ISSUE TITLE
S4PE won't let me edit anything!?

### ISSUE THREAD

**Issue by Ttaraab** [Kuree/Sims4Tools#57]
So i downloaded S4PE as i wanted to change some clothing categories but whenever i upload cc's it says 
Error reading resource 0x034AEECB-0x80000000-0xE06D1129A0204CF0
 Front-end Distribution: 
 Library Distribution: 

 Source: s4pi.WrapperDealer
 Assembly: s4pi.WrapperDealer, Version=1412.28.57.34111, Culture=neutral, PublicKeyToken=null
 Could not find a resource handler
 ----
 Stack trace:
 at s4pi.WrapperDealer.WrapperDealer.WrapperForType(String type, Int32 APIversion, Stream s)
 at s4pi.WrapperDealer.WrapperDealer.GetResource(Int32 APIversion, IPackage pkg, IResourceIndexEntry rie, Boolean AlwaysDefault)
 at S4PIDemoFE.MainForm.browserWidget1_SelectedResourceChanged(Object sender, ResourceChangedEventArgs e)
 ----

Also, the hex, preview and grid options at the bottom are greyed out and i can't click on them?

**Comment by Kuree** [comment]
Well, please use 7z to unzip the file. I will use the windows default unzipper to pack for the next release.
